test_that("HiCoolFile works", {
    mcool_path <- HiContactsData::HiContactsData('yeast_wt', 'mcool')
    pairs_path <- HiContactsData::HiContactsData('yeast_wt', 'pairs.gz')
    hcf <- HiCoolFile(mcool_path, resolution = 4000, pairs = pairs_path)
    expect_no_warning(show(hcf))
    expect_no_error(show(hcf))
    expect_equal(resolution(hcf), 4000L)
    expect_no_warning(pairsFile(hcf))
    expect_no_error(pairsFile(hcf))
})
