test_that("CoolFile works", {
    
    # Prepare paths and CoolFiles
    cool_path <- HiContactsData::HiContactsData('yeast_wt', 'cool')
    mcool_path <- HiContactsData::HiContactsData('yeast_wt', 'mcool')
    pairs_path <- HiContactsData::HiContactsData('yeast_wt', 'pairs.gz')
    cf0 <- CoolFile(cool_path)
    cf1 <- CoolFile(cool_path, pairsFile = pairs_path)
    mcf0 <- CoolFile(mcool_path)
    mcf1 <- CoolFile(mcool_path, pairsFile = pairs_path)
    mcf2 <- CoolFile(mcool_path, pairsFile = pairs_path, resolution = 16000)
    mcf3 <- CoolFile(mcool_path, resolution = 16000)

    # No errors/warnings when printing CoolFile
    expect_no_warning(show(cf0))
    expect_no_warning(cf0)
    expect_no_error(cf0)
    expect_no_warning(cf1)
    expect_no_error(cf1)
    expect_no_warning(mcf0)
    expect_no_error(mcf0)
    expect_no_warning(mcf1)
    expect_no_error(mcf1)
    expect_no_warning(mcf2)
    expect_no_error(mcf2)
    expect_no_warning(mcf3)
    expect_no_error(mcf3)

    # Resolution(s) are properly handled
    expect_null(resolution(cf0))
    expect_null(resolution(cf1))
    expect_equal(resolution(mcf0), 1000L)
    expect_equal(resolution(mcf1), 1000L)
    expect_equal(resolution(mcf2), 16000L)
    expect_equal(resolution(mcf3), 16000L)
    expect_no_error(CoolFile(cool_path, 1000L))
    expect_error(CoolFile(cool_path, 2000L))
    expect_error(CoolFile(mcool_path, 2))
    expect_no_error(metadata(mcf0) <- list(test = 'OK'))

    # pairFile is properly handled
    expect_null(pairsFile(cf0))
    expect_equal(pairsFile(cf1), pairs_path)
    expect_null(pairsFile(mcf0))
    expect_equal(pairsFile(mcf1), pairs_path)
    expect_equal(pairsFile(mcf2), pairs_path)
    expect_null(pairsFile(mcf3))

    # import is properly handled for CoolFile
    icf0 <- import(cf0, focus = 'I')
    icf1 <- import(cf1, focus = 'I')
    imcf0 <- import(mcf0, focus = 'I')
    imcf1 <- import(mcf1, focus = 'I')
    imcf2 <- import(mcf2)
    imcf3 <- import(mcf3)
    imcf4 <- import(mcf3, focus = 'I')
    imcf5 <- import(mcf3, resolution = 4000, focus = 'I', metadata = list(test = 'test'))
    expect_equal(resolution(icf0), 1000L)
    expect_null(pairsFile(icf0))
    expect_equal(resolution(icf1), 1000L)
    expect_equal(pairsFile(icf1), pairs_path)
    expect_equal(resolution(imcf0), 1000L)
    expect_null(pairsFile(imcf0))
    expect_equal(resolution(imcf1), 1000L)
    expect_equal(pairsFile(imcf1), pairs_path)
    expect_equal(resolution(imcf2), 16000L)
    expect_equal(pairsFile(imcf2), pairs_path)
    expect_equal(resolution(imcf3), 16000L)
    expect_null(pairsFile(imcf3))
    expect_null(focus(imcf3))
    expect_equal(metadata(imcf3), list())
    expect_equal(resolution(imcf4), 16000L)
    expect_null(pairsFile(imcf4))
    expect_equal(focus(imcf4), "I")
    expect_equal(resolution(imcf5), 4000L)
    expect_null(pairsFile(imcf5))
    expect_equal(metadata(imcf5), list(test = 'test'))
    expect_equal(focus(imcf5), "I")

    # import is properly handled for files provided as string
    icf0 <- import(cool_path, focus = 'I', format = 'cool')
    icf1 <- import(cool_path, focus = 'I', pairsFile = pairs_path, format = 'cool')
    imcf0 <- import(mcool_path, focus = 'I', format = 'cool')
    imcf1 <- import(mcool_path, focus = 'I', pairsFile = pairs_path, format = 'cool')
    imcf2 <- import(mcool_path, pairsFile = pairs_path, resolution = 16000, format = 'cool')
    imcf3 <- import(mcool_path, resolution = 16000, format = 'cool')
    imcf4 <- import(mcool_path, focus = 'I', format = 'cool')
    imcf5 <- import(mcool_path, resolution = 4000, focus = 'I', metadata = list(test = 'test'), format = 'cool')
    expect_equal(resolution(icf0), 1000L)
    expect_null(pairsFile(icf0))
    expect_equal(resolution(icf1), 1000L)
    expect_equal(pairsFile(icf1), pairs_path)
    expect_equal(resolution(imcf0), 1000L)
    expect_null(pairsFile(imcf0))
    expect_equal(resolution(imcf1), 1000L)
    expect_equal(pairsFile(imcf1), pairs_path)
    expect_equal(resolution(imcf2), 16000L)
    expect_equal(pairsFile(imcf2), pairs_path)
    expect_equal(resolution(imcf3), 16000L)
    expect_null(pairsFile(imcf3))
    expect_equal(resolution(imcf4), 1000L)
    expect_null(pairsFile(imcf4))
    expect_equal(focus(imcf4), "I")
    expect_equal(resolution(imcf5), 4000L)
    expect_null(pairsFile(imcf5))
    expect_equal(metadata(imcf5), list(test = 'test'))
    expect_equal(focus(imcf5), "I")

    # import is properly handled with HiCExperiment function
    expect_no_error(HiCExperiment(cool_path, focus = 'I'))
    expect_error(HiCExperiment(mcool_path, focus = 'I'))
    expect_error(HiCExperiment(mcool_path))
    ihf2 <- HiCExperiment(mcool_path, focus = 'I', resolution = 16000)
    ihf3 <- HiCExperiment(mcool_path, resolution = 16000, pairsFile = pairs_path)
    expect_equal(resolution(ihf2), 16000L)
    expect_equal(focus(ihf2), 'I')
    expect_null(pairsFile(ihf2))
    expect_equal(resolution(ihf3), 16000L)
    expect_null(focus(ihf3))
    expect_equal(pairsFile(ihf3), pairs_path)
    expect_equal(resolution(ihf3), 16000L)
    expect_null(focus(ihf3))

})
