#' @title `AggrHiCExperiment` S4 class
#' 
#' @name AggrHiCExperiment
#' @rdname AggrHiCExperiment
#' 
#' @description
#' 
#' The `AggrHiCExperiment` extends `HiCExperiment` class
#'
#' @slot fileName Path of Hi-C contact file
#' @slot resolutions Resolutions available in the Hi-C contact file.
#' @slot resolution Current resolution
#' @slot interactions Genomic Interactions extracted from the Hi-C contact file
#' @slot scores Available interaction scores. 
#' @slot slices Available interaction slices. 
#' @slot topologicalFeatures Topological features associated with the dataset 
#'   (e.g. loops (\<Pairs\>), borders (\<GRanges\>), 
#'   viewpoints (\<GRanges\>), etc...)
#' @slot pairsFile Path to the .pairs file associated with the Hi-C contact file
#' @slot metadata metadata associated with the Hi-C contact file.
#' 
#' @param file CoolFile or plain path to a Hi-C contact file
#' @param resolution Resolution to use with the Hi-C contact file
#' @param targets Set of chromosome coordinates for which 
#'   interaction counts are extracted from the Hi-C contact file, provided
#'   as a GRanges object (for diagnoal-centered loci) or as a GInteractions
#'   object (for off-diagonal coordinates).
#' @param metadata list of metadata
#' @param topologicalFeatures topologicalFeatures provided as a named SimpleList
#' @param pairsFile Path to an associated .pairs file
#' @param bed Path to regions file generated by HiC-Pro
#' @param BPPARAM BiocParallel parameters
#' 
#' @include HiCExperiment-class.R
#' @examples
#' microC <- HiCExperiment_example()
#' CTCF_peaks <- topologicalFeatures(microC, 'CTCF_peaks')
#' x <- AggrHiCExperiment(
#'   file = fileName(microC), 
#'   resolution = resolution(microC),
#'   targets = CTCF_peaks
#' )
#' x
#' slices(x, 'count')[, , 1]

methods::setClass("AggrHiCExperiment", contains = c("HiCExperiment"), 
    slots = c(slices = "SimpleList")
)

#' @rdname AggrHiCExperiment
#' @export

AggrHiCExperiment <- function(
    file, 
    resolution = NULL, 
    targets, 
    metadata = list(), 
    topologicalFeatures = S4Vectors::SimpleList(), 
    pairsFile = NULL, 
    bed = NULL, 
    BPPARAM = BiocParallel::bpparam()
) {
    file <- gsub('~', Sys.getenv('HOME'), file)
    stopifnot(file.exists(file))
    if (!is.null(resolution)) resolution <- as.integer(resolution)
    if (is_cool(file) | is_mcool(file)) {
        check_cool_file(file)
        check_cool_format(file, resolution)
        return(.aggrHiCExperiment(
            file = file,
            resolution = resolution,
            targets = targets,
            metadata = metadata,
            topologicalFeatures = topologicalFeatures,
            pairsFile = pairsFile, 
            BPPARAM = BPPARAM
        ))
    }
    if (is_hic(file)) {
        check_hic_file(file)
        check_hic_format(file, resolution)
        return(.aggrHiCExperiment(
            file = file,
            resolution = resolution,
            targets = targets,
            metadata = metadata,
            topologicalFeatures = topologicalFeatures,
            pairsFile = pairsFile, 
            BPPARAM = BPPARAM
        ))
    }
    if (is_hicpro_matrix(file)) {
        check_hicpro_files(file, bed)
        if (is.null(bed)) stop("Regions files not provided.")
        return(.aggrHiCExperiment(
            file = file,
            resolution = resolution,
            targets = targets,
            metadata = metadata,
            topologicalFeatures = topologicalFeatures,
            pairsFile = pairsFile, 
            bed = bed,
            BPPARAM = BPPARAM
        ))
    }
    return(NA)
}

#' @rdname AggrHiCExperiment

.aggrHiCExperiment <- function(
    file, 
    resolution = NULL, 
    targets, 
    metadata = list(), 
    topologicalFeatures = S4Vectors::SimpleList(), 
    pairsFile = NULL, 
    bed = NULL, 
    BPPARAM  
) {
    
    ## -- Parse multi-query
    if (is(targets, 'GRanges')) {

        # Need to check that targets are OK (unique width, greater than 0, ...)
        gis <- .multi2DQuery(
            file, resolution, 
            pairs = S4Vectors::Pairs(targets, targets), 
            bed = bed, 
            BPPARAM = BPPARAM
        )

    }
    else if (is(targets, 'GInteractions')) {

        # Need to check that pairs are OK (all width = 1)
        # Need to check that pairs are OK (distance between each pair > width of each anchor)
        targets <- InteractionSet::swapAnchors(targets)
        gis <- .multi2DQuery(
            file, resolution, 
            pairs = as(targets, 'Pairs'), 
            bed = bed, 
            BPPARAM = BPPARAM
        )

    }
    else {
        stop("Please provide `targets` as `GRanges` or `GInteractions`.")
    }
    mdata <- S4Vectors::metadata(gis)
    S4Vectors::metadata(gis) <- list()
    mcols <- GenomicRanges::mcols(gis)
    GenomicRanges::mcols(gis) <- NULL
    if (is.null(resolution)) {
        res <- ifelse({is_cool(file) | is_mcool(file)}, 
            lsCoolResolutions(file)[1], 
            ifelse(is_hic(file), lsHicResolutions(file)[1], 
            GenomicRanges::width(.getHicproAnchors(bed))[1])
        )
    }
    if (is_cool(file) | is_mcool(file)) {
        resolutions <- lsCoolResolutions(file)
    }
    else if (is_hic(file)) {
        resolutions <- lsHicResolutions(file)
    }
    else if (is_hicpro_matrix(file)) {
        resolutions <- res
    }
    
    ## -- Create contact object
    x <- methods::new("AggrHiCExperiment", 
        fileName = as.character(file),
        focus = "aggregated targets", 
        resolutions = resolutions, 
        resolution = res, 
        interactions = gis, 
        scores = S4Vectors::SimpleList(
            'count' = as.numeric(mcols$count), 
            'balanced' = as.numeric(mcols$balanced), 
            'expected' = as.numeric(mcols$expected), 
            'detrended' = as.numeric(mcols$detrended)
        ),
        slices = mdata$slices, 
        topologicalFeatures = S4Vectors::SimpleList(
            c(targets = targets, as.list(topologicalFeatures))
        ),
        pairsFile = pairsFile, 
        metadata = metadata
    )
    methods::validObject(x)
    return(x)
} 
