#' @importClassesFrom GenomicRanges GRanges
#' @importClassesFrom InteractionSet GInteractions

setClassUnion("GRangesOrGInteractions", members = c("GRanges", "GInteractions"))
setClassUnion("characterOrNULL", members = c("character", "NULL"))
setClassUnion("numericOrNULL", members = c("numeric", "NULL"))

#' @title `HiCExperiment` S4 class
#' 
#' @name HiCExperiment
#' @rdname HiCExperiment
#' 
#' @description
#' 
#' The `HiCExperiment` class describes Hi-C contact files imported in R, either 
#' through the `HiCExperiment` constructor function or using the `import` 
#' method implemented by `HiCExperiment` package. 
#'
#' @slot fileName Path of Hi-C contact file
#' @slot focus Chr. coordinates for which interaction counts are extracted 
#'   from the Hi-C contact file.
#' @slot resolutions Resolutions available in the Hi-C contact file.
#' @slot resolution Current resolution
#' @slot interactions Genomic Interactions extracted from the Hi-C contact file
#' @slot scores Available interaction scores. 
#' @slot topologicalFeatures Topological features associated with the dataset 
#'   (e.g. loops (\<Pairs\>), borders (\<GRanges\>), 
#'   viewpoints (\<GRanges\>), etc...)
#' @slot pairsFile Path to the .pairs file associated with the Hi-C contact file
#' @slot metadata metadata associated with the Hi-C contact file.
#' 
#' @param file CoolFile or plain path to a Hi-C contact file
#' @param resolution Resolution to use with the Hi-C contact file
#' @param focus Chromosome coordinates for which 
#'   interaction counts are extracted from the Hi-C contact file, provided
#'   as a character string (e.g. "II:4000-5000"). If not provided, 
#'   the entire Hi-C contact file will be imported. 
#' @param metadata list of metadata
#' @param topologicalFeatures topologicalFeatures provided as a named SimpleList
#' @param pairsFile Path to an associated .pairs file (optional)
#' @param bed Path to regions file generated by HiC-Pro (optional)
#' 
#' @return An `HiCExperiment` object.
#' 
#' @importFrom methods setClass
#' @importClassesFrom S4Vectors Annotated
#' @importFrom S4Vectors metadata
#' @examples 
#' mcool_path <- HiContactsData::HiContactsData('yeast_wt', 'mcool')
#' contacts_yeast <- HiCExperiment(mcool_path, resolution = 16000, focus = 'II')
#' contacts_yeast
#' resolutions(contacts_yeast)
#' resolution(contacts_yeast)
#' focus(contacts_yeast)
#' scores(contacts_yeast)
#' tail(scores(contacts_yeast, 1))
#' tail(scores(contacts_yeast, 'balanced'))
#' scores(contacts_yeast, 'test') <- runif(length(contacts_yeast))
#' tail(scores(contacts_yeast, 'test'))
#' data(centros_yeast)
#' topologicalFeatures(contacts_yeast, 'centromeres') <- centros_yeast
#' topologicalFeatures(contacts_yeast, 1)
#' topologicalFeatures(contacts_yeast, 'centromeres')
#' pairsFile(contacts_yeast)
#' fileName(contacts_yeast)
#' interactions(contacts_yeast)
#' length(contacts_yeast)
#' contacts_yeast[seq_len(10)]
#' seqinfo(contacts_yeast)
#' bins(contacts_yeast)
#' anchors(contacts_yeast)
#' regions(contacts_yeast)
#' contacts_yeast
#' as(contacts_yeast, 'GInteractions')
#' as(contacts_yeast, 'ContactMatrix')
#' as(contacts_yeast, 'matrix')[seq_len(10), seq_len(10)]
#' as(contacts_yeast, 'data.frame')[seq_len(10), seq_len(10)]

NULL

#' @rdname HiCExperiment
#' @export

methods::setClass("HiCExperiment", 
    contains = c("Annotated"), 
    slots = c(
        fileName = "character",
        focus = "characterOrNULL", 
        resolutions = "numeric", 
        resolution = "numeric", 
        interactions = "GInteractions",
        scores = "SimpleList", 
        topologicalFeatures = "SimpleList",
        pairsFile = "characterOrNULL",
        metadata = "list"
    )
)

#' @rdname HiCExperiment
#' @export

HiCExperiment <- function(
    file, 
    resolution = NULL, 
    focus = NULL, 
    metadata = list(), 
    topologicalFeatures = S4Vectors::SimpleList(
        'compartments' = GenomicRanges::GRanges(), 
        'borders' = GenomicRanges::GRanges(), 
        'loops' = InteractionSet::GInteractions(
            GenomicRanges::GRanges(), 
            GenomicRanges::GRanges()
        ), 
        'viewpoints' = GenomicRanges::GRanges()
    ), 
    pairsFile = NULL, 
    bed = NULL
) {
    file <- gsub('~', Sys.getenv('HOME'), file)
    stopifnot(file.exists(file))
    if (!is.null(resolution)) resolution <- as.integer(resolution)
    
    if (is_cool(file) | is_mcool(file)) {
        return(.HiCExperimentFromCoolFile(
            file = file,
            resolution = resolution,
            focus = focus,
            metadata = metadata,
            topologicalFeatures = topologicalFeatures,
            pairsFile = pairsFile
        ))
    }
    if (is_hic(file)) {
        return(.HiCExperimentFromHicFile(
            file = file,
            resolution = resolution,
            focus = focus,
            metadata = metadata,
            topologicalFeatures = topologicalFeatures,
            pairsFile = pairsFile
        ))
    }
    if (is_hicpro_matrix(file)) {
        if (is.null(bed)) stop("Regions files not provided.")
        if (!is.null(resolution)) stop("Resolution cannot be specified when importing HiC-Pro files.")
        if (!is.null(focus)) stop("Focus cannot be specified when importing HiC-Pro files.")
        return(.HiCExperimentFromHicproFile(
            file = file,
            bed = bed,
            metadata = metadata,
            topologicalFeatures = topologicalFeatures,
            pairsFile = pairsFile
        ))
    }
    return(NA)
}

setValidity("HiCExperiment",
    function(object) {
        if (!is(focus(object), "characterOrNULL"))
            return("'focus' slot must be a characterOrNULL")
        if (!is(resolutions(object), "numeric"))
            return("'resolutions' slot must be an numeric vector")
        if (!is(scores(object), "SimpleList"))
            return("'scores' slot must be a SimpleList")
        TRUE
    }
)

#' @rdname HiCExperiment

.HiCExperimentFromCoolFile <- function(
    file, 
    resolution = NULL, 
    focus = NULL, 
    metadata = list(), 
    topologicalFeatures = S4Vectors::SimpleList(
        'compartments' = GenomicRanges::GRanges(), 
        'borders' = GenomicRanges::GRanges(), 
        'loops' = InteractionSet::GInteractions(
            GenomicRanges::GRanges(), 
            GenomicRanges::GRanges()
        ), 
        'viewpoints' = GenomicRanges::GRanges()
    ), 
    pairsFile = NULL
) {
    
    ## -- Check that provided file is valid
    file <- gsub('~', Sys.getenv('HOME'), file)
    check_cool_file(file)
    check_cool_format(file, resolution)

    ## -- Read interactions
    gis <- .cool2gi(file, resolution = resolution, coords = focus) |> sort()
    mcols <- GenomicRanges::mcols(gis)
    GenomicRanges::mcols(gis) <- mcols[, c('bin_id1', 'bin_id2')]

    ## -- Create contact object
    x <- methods::new("HiCExperiment", 
        fileName = as.character(file),
        focus = focus, 
        resolutions = lsCoolResolutions(file), 
        resolution = ifelse(is.null(resolution), lsCoolResolutions(file)[1], resolution), 
        interactions = gis, 
        scores = S4Vectors::SimpleList(
            'count' = as.numeric(mcols$count),
            'balanced' = as.numeric(mcols$score)
        ), 
        topologicalFeatures = topologicalFeatures, 
        pairsFile = pairsFile, 
        metadata = metadata
    )
    methods::validObject(x)
    return(x)
} 

#' @rdname HiCExperiment

.HiCExperimentFromHicFile <- function(
    file, 
    resolution = NULL, 
    focus = NULL, 
    metadata = list(), 
    topologicalFeatures = S4Vectors::SimpleList(
        'compartments' = GenomicRanges::GRanges(), 
        'borders' = GenomicRanges::GRanges(), 
        'loops' = InteractionSet::GInteractions(
            GenomicRanges::GRanges(), 
            GenomicRanges::GRanges()
        ), 
        'viewpoints' = GenomicRanges::GRanges()
    ), 
    pairsFile = NULL
) {
    
    ## -- Check that provided file is valid
    file <- gsub('~', Sys.getenv('HOME'), file)
    check_hic_file(file)
    check_hic_format(file, resolution)

    ## -- Read interactions
    gis <- .hic2gi(file, resolution = resolution, coords = focus) |> sort()
    mcols <- GenomicRanges::mcols(gis)
    GenomicRanges::mcols(gis) <- mcols[, c('bin_id1', 'bin_id2')]

    ## -- Create HiCExperiment
    if (!is.null(focus)) focus <- gsub("(:.*[^:]*):", "\\1-", focus)
    x <- methods::new("HiCExperiment", 
        fileName = as.character(file),
        focus = focus, 
        resolutions = rev(strawr::readHicBpResolutions(file)), 
        resolution = resolution, 
        interactions = gis, 
        scores = S4Vectors::SimpleList(
            'count' = as.numeric(mcols$count),
            'balanced' = as.numeric(mcols$score)
        ), 
        topologicalFeatures = topologicalFeatures, 
        pairsFile = pairsFile, 
        metadata = metadata
    )
    methods::validObject(x)
    return(x)
} 

#' @rdname HiCExperiment

.HiCExperimentFromHicproFile <- function(
    file, 
    bed, 
    metadata = list(), 
    topologicalFeatures = S4Vectors::SimpleList(
        'compartments' = GenomicRanges::GRanges(), 
        'borders' = GenomicRanges::GRanges(), 
        'loops' = InteractionSet::GInteractions(
            GenomicRanges::GRanges(), 
            GenomicRanges::GRanges()
        ), 
        'viewpoints' = GenomicRanges::GRanges()
    ), 
    pairsFile = NULL
) {
    
    ## -- Check that provided file is valid
    file <- gsub('~', Sys.getenv('HOME'), file)
    check_hicpro_files(file, bed)

    ## -- Read interactions
    gis <- .hicpro2gi(file, bed) |> sort()
    mcols <- GenomicRanges::mcols(gis)
    GenomicRanges::mcols(gis) <- mcols[, c('bin_id1', 'bin_id2')]
    res <- GenomicRanges::width(regions(gis))[[1]]

    ## -- Create HiCExperiment
    x <- methods::new("HiCExperiment", 
        fileName = as.character(file),
        focus = NULL, 
        resolutions = res, 
        resolution = res, 
        interactions = gis, 
        scores = S4Vectors::SimpleList(
            'count' = as.numeric(mcols$count)
        ), 
        topologicalFeatures = topologicalFeatures, 
        pairsFile = pairsFile, 
        metadata = c(list(regions = bed), metadata)
    )
    methods::validObject(x)
    return(x)
} 
